spring.datasource.url=jdbc:postgresql://localhost:5434/fingerprint?options=-c%20timezone=Asia/Ho_Chi_Minh
spring.datasource.username=admin
spring.datasource.password=19981999
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.signerKey=pX32s83jjYQLxJumZB8BSqi6JvwAprhZ072MrE6xVrs=
# Cho phép upload file lên ??n 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB