spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/fingerprint?currentSchema=fingerprint}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:19981999}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=spring
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-init-sql=SET search_path TO spring, public
jwt.signerKey=${JWT_SIGNER_KEY:pX32s83jjYQLxJumZB8BSqi6JvwAprhZ072MrE6xVrs=}

tracing.python-base-url=${TRACING_PYTHON_URL:http://localhost:8000}
tracing.internal-service-key=${INTERNAL_SERVICE_KEY:tracing-internal}
file.upload-dir=${FILE_UPLOAD_DIR:uploads}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
